# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient_RazgulyaevSergey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~>5.2'
  pod 'RealmSwift', '= 5.3.5'
  pod 'SDWebImage', '=5.0'

  # Pods for VKClient_RazgulyaevSergey

end
